onehot_feature_list = ['Via Medio de Transporte - DDT_AIRE',
                    'Via Medio de Transporte - DDT_HIDRO',
                    'Via Medio de Transporte - DDT_MAR',
                    'Via Medio de Transporte - DDT_OTRO',
                    'Via Medio de Transporte - DDT_TIERRA',
                    'Mercaderia uso - ART_1',
                    'Mercaderia uso - ART_2',
                    'Mercaderia uso - ART_3',
                    'Mercaderia uso - ART_4',
                    'Mercaderia uso - ART_5',
                    'Mercaderia uso - ART_6',
                    'Destinacion_XX_DI',
                    'Destinacion_XX_IC',
                    'Destinacion_XX_IG',
                    'Destinacion_XX_IS',
                    'Destinacion_XX_IT',
                    'Destinacion_XX_TG',
                    'Destinacion_XX_ZF',
                    'day_of_week_0',
                    'day_of_week_1',
                    'day_of_week_2',
                    'day_of_week_3',
                    'day_of_week_4',
                    'day_of_week_5',
                    'day_of_week_6']